### ISSUE TITLE
webpack config for scss

### ISSUE THREAD

**Issue by colinmccann** [encorelab/ckx#12]
I tried a couple things, but couldn't get anything working... any ideas @houshuang?

**Comment by houshuang** [comment]
Will look at this more in-depth later, but did you try require() instead of
import?

On Wed, Jul 6, 2016 at 8:42 PM, colinmccann notifications@github.com
wrote:

> I tried a couple things, but couldn't get anything working... any ideas
> @houshuang https://github.com/houshuang
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/encorelab/ckx/issues/12, or mute the thread
> https://github.com/notifications/unsubscribe/AADwh5DncWmZeyfL5aFVS_TXSv_qPoT2ks5qTEuOgaJpZM4JGoyF
> .

## 

http://reganmian.net/blog -- Random Stuff that Matters

**Comment by colinmccann** [comment]
I have - that could work as well. Was just continuing to mimic Matt's
suggested structuring for this. Am also worried about what happens when we
head to prod...

On Wed, Jul 6, 2016 at 8:45 PM, Stian Håklev notifications@github.com
wrote:

> Will look at this more in-depth later, but did you try require() instead of
> import?
> 
> On Wed, Jul 6, 2016 at 8:42 PM, colinmccann notifications@github.com
> wrote:
> 
> > I tried a couple things, but couldn't get anything working... any ideas
> > @houshuang https://github.com/houshuang
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > https://github.com/encorelab/ckx/issues/12, or mute the thread
> > <
> > https://github.com/notifications/unsubscribe/AADwh5DncWmZeyfL5aFVS_TXSv_qPoT2ks5qTEuOgaJpZM4JGoyF
> > 
> > .
> 
> ## 
> 
> http://reganmian.net/blog -- Random Stuff that Matters
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/encorelab/ckx/issues/12#issuecomment-230949179, or mute
> the thread
> https://github.com/notifications/unsubscribe/AAuEmPSJPBLGc6gf6k31zGTofIoe3pkcks5qTEwzgaJpZM4JGoyF
> .

## 

Colin

**Comment by houshuang** [comment]
I'll need to look at this more in-depth. Not today or tomorrow though.

On Wed, Jul 6, 2016 at 8:47 PM, colinmccann notifications@github.com
wrote:

> I have - that could work as well. Was just continuing to mimic Matt's
> suggested structuring for this. Am also worried about what happens when we
> head to prod...
> 
> On Wed, Jul 6, 2016 at 8:45 PM, Stian Håklev notifications@github.com
> wrote:
> 
> > Will look at this more in-depth later, but did you try require() instead
> > of
> > import?
> > 
> > On Wed, Jul 6, 2016 at 8:42 PM, colinmccann notifications@github.com
> > wrote:
> > 
> > > I tried a couple things, but couldn't get anything working... any ideas
> > > @houshuang https://github.com/houshuang
> > > 
> > > —
> > > You are receiving this because you were mentioned.
> > > Reply to this email directly, view it on GitHub
> > > https://github.com/encorelab/ckx/issues/12, or mute the thread
> > > <
> > 
> > https://github.com/notifications/unsubscribe/AADwh5DncWmZeyfL5aFVS_TXSv_qPoT2ks5qTEuOgaJpZM4JGoyF
> > 
> > > .
> > 
> > ## 
> > 
> > http://reganmian.net/blog -- Random Stuff that Matters
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > https://github.com/encorelab/ckx/issues/12#issuecomment-230949179, or
> > mute
> > the thread
> > <
> > https://github.com/notifications/unsubscribe/AAuEmPSJPBLGc6gf6k31zGTofIoe3pkcks5qTEwzgaJpZM4JGoyF
> > 
> > .
> 
> ## 
> 
> Colin
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/encorelab/ckx/issues/12#issuecomment-230949421, or mute
> the thread
> https://github.com/notifications/unsubscribe/AADwh6fQLTTME4kLqv-TlZPW_naGqspvks5qTEyWgaJpZM4JGoyF
> .

## 

http://reganmian.net/blog -- Random Stuff that Matters

**Comment by colinmccann** [comment]
All good, no rush. I might spend some time on it tomorrow anyways, since I
need to understand the webpack structures anyways...

On Wed, Jul 6, 2016 at 8:59 PM, Stian Håklev notifications@github.com
wrote:

> I'll need to look at this more in-depth. Not today or tomorrow though.
> 
> On Wed, Jul 6, 2016 at 8:47 PM, colinmccann notifications@github.com
> wrote:
> 
> > I have - that could work as well. Was just continuing to mimic Matt's
> > suggested structuring for this. Am also worried about what happens when
> > we
> > head to prod...
> > 
> > On Wed, Jul 6, 2016 at 8:45 PM, Stian Håklev notifications@github.com
> > wrote:
> > 
> > > Will look at this more in-depth later, but did you try require()
> > > instead
> > > of
> > > import?
> > > 
> > > On Wed, Jul 6, 2016 at 8:42 PM, colinmccann notifications@github.com
> > > wrote:
> > > 
> > > > I tried a couple things, but couldn't get anything working... any
> > > > ideas
> > > > @houshuang https://github.com/houshuang
> > > > 
> > > > —
> > > > You are receiving this because you were mentioned.
> > > > Reply to this email directly, view it on GitHub
> > > > https://github.com/encorelab/ckx/issues/12, or mute the thread
> > > > <
> > 
> > https://github.com/notifications/unsubscribe/AADwh5DncWmZeyfL5aFVS_TXSv_qPoT2ks5qTEuOgaJpZM4JGoyF
> > 
> > > > .
> > > 
> > > ## 
> > > 
> > > http://reganmian.net/blog -- Random Stuff that Matters
> > > 
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly, view it on GitHub
> > > https://github.com/encorelab/ckx/issues/12#issuecomment-230949179,
> > > or
> > > mute
> > > the thread
> > > <
> > 
> > https://github.com/notifications/unsubscribe/AAuEmPSJPBLGc6gf6k31zGTofIoe3pkcks5qTEwzgaJpZM4JGoyF
> > 
> > > .
> > 
> > ## 
> > 
> > Colin
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > https://github.com/encorelab/ckx/issues/12#issuecomment-230949421, or
> > mute
> > the thread
> > <
> > https://github.com/notifications/unsubscribe/AADwh6fQLTTME4kLqv-TlZPW_naGqspvks5qTEyWgaJpZM4JGoyF
> > 
> > .
> 
> ## 
> 
> http://reganmian.net/blog -- Random Stuff that Matters
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/encorelab/ckx/issues/12#issuecomment-230950992, or mute
> the thread
> https://github.com/notifications/unsubscribe/AAuEmLSYvDB_EIi6XxPVTMxj5snx7Ktuks5qTE9ogaJpZM4JGoyF
> .

## 

Colin
