### ISSUE TITLE
jwt expiration

### ISSUE THREAD

**Issue by colinmccann** [encorelab/ckx#2]
Still seeing the "jwt expired" error on startup. Can be resolved with a cache clear, but preferable to have a: better user notification that this is the issue and/or b: some cleaner way of resolving this. See attached
<img width="1407" alt="screen shot 2016-05-24 at 7 15 04 pm" src="https://cloud.githubusercontent.com/assets/754840/15523003/d9dfb5f2-21e4-11e6-9386-9a5cf3e5bc80.png">

**Comment by houshuang** [comment]
This code was in houshuang/ckx, but must have fallen out of the transition to encorelab. Reopen again if the problem persists.
