### ISSUE TITLE
db/collection missing on new installs

### ISSUE THREAD

**Issue by colinmccann** [encorelab/ckx#3]
We have database setup errors on new installs. No obvious negative outcomes, so maybe we can safely ignore (famous last works).

To dup, clone the repo and run the install script. Start the servers, load localhost. Keep an eye on the hz console.
<img width="1325" alt="screen shot 2016-05-18 at 2 07 21 pm" src="https://cloud.githubusercontent.com/assets/754840/15523090/be6299ce-21e5-11e6-8d44-73abce6226db.png">
<img width="1256" alt="screen shot 2016-05-18 at 2 07 10 pm" src="https://cloud.githubusercontent.com/assets/754840/15523100/d7d22d3e-21e5-11e6-9146-d37fb9dbdce9.png">

**Comment by houshuang** [comment]
This is fine, the collections are created on request, but takes a few seconds to get set up, and in the meantime attempts to connect to them don't work. Once the collections are created, the connection is set up, and all is well.

Eventually we will turn off this "dev" functionality, and manage collection-creation from the login module (creating a new collaborative object also creates a new collection to hold it, etc).

Reopen if this seems to create bugs in the UI etc.
